#!/bin/bash

function install_cpp_tools() {
    sudo apt-get install -y \
        build-essential \
        gdb \
        cmake \
        valgrind \
        cppcheck \
        clang-format \
        libboost-all-dev
}

function setup_python_env() {
    sudo apt-get install -y python3 python3-venv python3-pip

    mkdir -p "$HOME/.mylinux/python"
    
    if [ ! -d "$HOME/.mylinux/python/venv" ]; then
        python3 -m venv "$HOME/.mylinux/python/venv"
    fi

    "$HOME/.mylinux/python/venv/bin/pip" install --upgrade pip
    "$HOME/.mylinux/python/venv/bin/pip" install \
        numpy \
        scipy \
        matplotlib \
        sympy \
        requests \
        ipython
}

function install_apps() {
    sudo apt-get install -y \
        micro \
        strawberry \
        vlc \
        qbittorrent
}

function main() {
    install_cpp_tools
    setup_python_env
    install_apps
}

main
